# fly.toml app configuration file generated for tucano-server on 2024-09-22T19:40:14-03:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'tucano-server'
primary_region = 'gru'

[build]

[http_service]
  internal_port = 443
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  size = 'shared-cpu-1x'
